### ISSUE TITLE
Provide var for template path

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/ansible-role-riemann#13]
Users of the role should be able to write their own riemann config from scratch and have this role apply it. A simple var like `riemann_config_src: riemann.config.j2` would suffice.

**Comment by msheiny** [comment]
PING!!!

**Comment by msheiny** [comment]
Come on webhook!

**Comment by conorsch** [comment]
Testing integration...

**Comment by conorsch** [comment]
Testing integration again...

**Comment by conorsch** [comment]
Closed via #15.
